Skahr\SaltCityBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        login:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255