Skahr\SaltCityBundle\Entity\Sale:
    type: entity
    table: sale
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        salestext:
            type: text
        status:
            type: integer
            nullable: true
        cat:
            type: integer
        datecr:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setDatecrValue ]