admin:
    path:     /
    defaults: { _controller: "SkahrSaltCityBundle:Admin:index" }

admin_passchange:
    path:     /change
    defaults: { _controller: "SkahrSaltCityBundle:Admin:passChange" }
    methods:  POST
admin_login:
    path:     /login
    defaults: { _controller: "SkahrSaltCityBundle:Admin:login" }
    methods:  POST
admin_logout:
    path:     /logout
    defaults: { _controller: "SkahrSaltCityBundle:Admin:logout" }
admin_passreset:
    path:     /reset
    defaults: { _controller: "SkahrSaltCityBundle:Admin:passReset" }
    methods:  POST
admin_passresetcheck:
    path:     /check/{id}/{hash}
    defaults: { _controller: "SkahrSaltCityBundle:Admin:passResetCheck" }
admin_passresetcheckpost:
    path:     /checkpost/{id}/{hash}
    defaults: { _controller: "SkahrSaltCityBundle:Admin:passResetCheckPost" }
    methods:  POST