news:
    path:     /
    defaults: { _controller: "SkahrSaltCityBundle:News:index" }

news_show:
    path:     /{id}/show
    defaults: { _controller: "SkahrSaltCityBundle:News:show" }

news_new:
    path:     /new
    defaults: { _controller: "SkahrSaltCityBundle:News:new" }

news_create:
    path:     /create
    defaults: { _controller: "SkahrSaltCityBundle:News:create" }
    methods:  POST

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkahrSaltCityBundle:News:edit" }

news_update:
    path:     /{id}/update
    defaults: { _controller: "SkahrSaltCityBundle:News:update" }
    methods:  [POST, PUT]

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkahrSaltCityBundle:News:delete" }
    methods:  [POST, DELETE]
