skahr_salt_city_admin:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/admin.yml"
    prefix:   /saltmaster

SkahrSaltCityBundle_sale:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/sale.yml"
    prefix:   /sale

SkahrSaltCityBundle_price:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/price.yml"
    prefix:   /price

SkahrSaltCityBundle_comment:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

SkahrSaltCityBundle_homepage:
    pattern:  /
    defaults: { _controller: SkahrSaltCityBundle:Page:index }
    requirements:
        _method:  GET
SkahrSaltCityBundle_salt_photo:
    pattern: /salt/photo/{id}
    defaults: { _controller: SkahrSaltCityBundle:Page:saltPhoto, id: 0 }
    requirements:
        _method: GET