skahr_salt_city_admin:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

SkahrSaltCityBundle_sale:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/sale.yml"
    prefix:   /sale

SkahrSaltCityBundle_price:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/price.yml"
    prefix:   /price

SkahrSaltCityBundle_comment:
    resource: "@SkahrSaltCityBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

SkahrSaltCityBundle_homepage:
    pattern:  /
    defaults: { _controller: SkahrSaltCityBundle:Page:index }
    requirements:
        _method:  GET
SkahrSaltCityBundle_contacts:
    pattern: /contacts
    defaults: { _controller: SkahrSaltCityBundle:Page:contacts }
    requirements:
        _method: GET
SkahrSaltCityBundle_salt:
    pattern: /salt
    defaults: { _controller: SkahrSaltCityBundle:Page:salt }
    requirements:
        _method: GET
SkahrSaltCityBundle_salt_photo:
    pattern: /salt/photo/{id}
    defaults: { _controller: SkahrSaltCityBundle:Page:saltPhoto, id: 0 }
    requirements:
        _method: GET
SkahrSaltCityBundle_salt_rules:
    pattern: /salt/rules
    defaults: { _controller: SkahrSaltCityBundle:Page:saltRules }
    requirements:
        _method: GET
SkahrSaltCityBundle_salt_indications:
    pattern: /salt/indications
    defaults: { _controller: SkahrSaltCityBundle:Page:saltIndications }
    requirements:
        _method: GET
SkahrSaltCityBundle_salt_contraindications:
    pattern: /salt/contr
    defaults: { _controller: SkahrSaltCityBundle:Page:saltContraindications }
    requirements:
        _method: GET
SkahrSaltCityBundle_salt_cert:
    pattern: /salt/cert
    defaults: { _controller: SkahrSaltCityBundle:Page:saltCert }
    requirements:
        _method: GET
